"""
====================================================================

Topic:
    Conversation Memory using LCEL (LangChain Expression Language)

Objective:
    Learn how to maintain conversation history and pass it to an LLM
    using LangChain's MessagesPlaceholder.

Concepts Covered:
    1. HumanMessage
    2. AIMessage
    3. chat_history
    4. MessagesPlaceholder
    5. ChatPromptTemplate
    6. ChatOllama
    7. StrOutputParser
    8. LCEL Pipeline

Why Conversation Memory?

Without memory:

User:
    What is LangChain?

AI:
    LangChain is an LLM framework.

User:
    Who created it?

The AI only sees:
    "Who created it?"

It doesn't know what "it" refers to.

With Conversation Memory:

The AI receives:

----------------------------------------
User:
What is LangChain?

AI:
LangChain is an LLM framework.

User:
Who created it?
----------------------------------------

Now it understands:

it --> LangChain

====================================================================

Architecture

                chat_history
                      |
                      |
                      v

          MessagesPlaceholder
                      |
                      |
                      v

          ChatPromptTemplate
                      |
                      |
                      v

              ChatOllama
                      |
                      |
                      v

           StrOutputParser
                      |
                      |
                      v

                Final Answer

====================================================================
"""

# ============================
# Import Required Modules
# ============================

from langchain_core.messages import (
    HumanMessage,
    AIMessage
)

from langchain_core.prompts import (
    ChatPromptTemplate,
    MessagesPlaceholder
)

from langchain_ollama import ChatOllama
from langchain_core.output_parsers import StrOutputParser


# ==============================================================
# Step 1 : Create Conversation Memory
# ==============================================================

"""
chat_history stores the previous conversation.

HumanMessage -> Message sent by user

AIMessage -> Response generated by AI

LangChain stores messages as objects instead of strings
because it needs to know WHO sent each message.
"""

chat_history = [

    HumanMessage(
        content="What is LangChain?"
    ),

    AIMessage(
        content="LangChain is a framework for building LLM applications."
    )
]


# ==============================================================
# Step 2 : Create Prompt
# ==============================================================

"""
MessagesPlaceholder dynamically inserts chat_history
into the prompt.

The prompt sent to the LLM becomes:

----------------------------------------

System:
You are a helpful AI Tutor.

Human:
What is LangChain?

AI:
LangChain is a framework for building LLM applications.

Human:
Who created it?

----------------------------------------
"""

prompt = ChatPromptTemplate.from_messages(

    [

        (
            "system",
            "You are a helpful AI tutor."
        ),

        MessagesPlaceholder(
            variable_name="chat_history"
        ),

        (
            "human",
            "{question}"
        )

    ]

)


# ==============================================================
# Step 3 : Load LLM
# ==============================================================

llm = ChatOllama(
    model="llama3:latest"
)


# ==============================================================
# Step 4 : Output Parser
# ==============================================================

"""
ChatOllama returns an AIMessage object.

StrOutputParser converts it into a normal Python string.
"""

parser = StrOutputParser()


# ==============================================================
# Step 5 : Create LCEL Chain
# ==============================================================

"""
LCEL Pipeline

Prompt
   |
   v
LLM
   |
   v
Output Parser
"""

chain = (

    prompt
    |
    llm
    |
    parser

)


# ==============================================================
# Step 6 : Ask Follow-up Question
# ==============================================================

question = "Who created it?"


# ==============================================================
# Step 7 : Invoke Chain
# ==============================================================

response = chain.invoke(

    {

        "chat_history": chat_history,

        "question": question

    }

)


# ==============================================================
# Step 8 : Print Response
# ==============================================================

print("\n==============================")
print("Conversation History")
print("==============================")

for message in chat_history:

    if isinstance(message, HumanMessage):

        print(f"User      : {message.content}")

    elif isinstance(message, AIMessage):

        print(f"Assistant : {message.content}")


print("\n==============================")
print("Current Question")
print("==============================")

print(question)


print("\n==============================")
print("AI Response")
print("==============================")

print(response)


# ==============================================================
# Step 9 : Update Conversation Memory
# ==============================================================

"""
After receiving the response,
store the latest conversation.

This enables multi-turn conversations.
"""

chat_history.append(

    HumanMessage(
        content=question
    )

)

chat_history.append(

    AIMessage(
        content=response
    )

)


# ==============================================================
# Step 10 : Display Updated Memory
# ==============================================================

print("\n==============================")
print("Updated Conversation History")
print("==============================")

for message in chat_history:

    if isinstance(message, HumanMessage):

        print(f"User      : {message.content}")

    else:

        print(f"Assistant : {message.content}")


"""
====================================================================

Summary

HumanMessage
------------
Represents a message sent by the user.

AIMessage
---------
Represents a message generated by the AI.

chat_history
------------
Stores the complete conversation.

MessagesPlaceholder
-------------------
Inserts chat_history into the prompt.

ChatPromptTemplate
------------------
Creates the final prompt.

ChatOllama
----------
Generates the response.

StrOutputParser
---------------
Converts AIMessage into plain text.

LCEL
----
Prompt
   |
   v
LLM
   |
   v
Parser

====================================================================
"""